# Generated by Django 5.0.1 on 2024-01-17 04:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('title_kk', models.CharField(max_length=300, verbose_name='наименование на казахском')),
                ('title_ru', models.CharField(max_length=300, verbose_name='наименование на русском')),
                ('title_en', models.CharField(max_length=300, verbose_name='наименование на английском')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='фото')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='json данные')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kk', models.CharField(max_length=300, verbose_name='наименование на казахском')),
                ('title_ru', models.CharField(max_length=300, verbose_name='наименование на русском')),
                ('title_en', models.CharField(max_length=300, verbose_name='наименование на английском')),
            ],
            options={
                'verbose_name': 'район',
                'verbose_name_plural': 'районы',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kk', models.CharField(max_length=300, verbose_name='наименование на казахском')),
                ('title_ru', models.CharField(max_length=300, verbose_name='наименование на русском')),
                ('title_en', models.CharField(max_length=300, verbose_name='наименование на английском')),
            ],
            options={
                'verbose_name': 'область',
                'verbose_name_plural': 'области',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='активность')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('date_of_action', models.DateField(blank=True, null=True, verbose_name='дата происшествия')),
                ('title_kk', models.CharField(max_length=300, verbose_name='наименование на казахском')),
                ('title_ru', models.CharField(max_length=300, verbose_name='наименование на русском')),
                ('title_en', models.CharField(verbose_name='наименование на английском')),
                ('text_kk', models.TextField(verbose_name='описание на казахском')),
                ('text_ru', models.TextField(verbose_name='описание на русском')),
                ('text_en', models.TextField(verbose_name='описание на английском')),
                ('media', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='media/', verbose_name='медиа-файлы'), size=None)),
                ('data', models.JSONField(blank=True, null=True, verbose_name='json данные')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='info_change_users', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='info_create_users', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='активность')),
                ('punkt_kk', models.CharField(max_length=150, verbose_name='населеный пункт на казахском')),
                ('punkt_ru', models.CharField(max_length=150, verbose_name='населеный пункт на русском')),
                ('punkt_en', models.CharField(max_length=150, verbose_name='населеный пункт на английском')),
                ('date_of_action', models.DateField(verbose_name='дата происшествия (утери/похищения)')),
                ('time_of_action', models.TimeField(verbose_name='время происшествия (утери/похищения)')),
                ('title_kk', models.CharField(max_length=300, verbose_name='наименование на казахском')),
                ('title_ru', models.CharField(max_length=300, verbose_name='наименование на русском')),
                ('title_en', models.CharField(max_length=300, verbose_name='наименование на английском')),
                ('text_kk', models.TextField(verbose_name='описание на казахском')),
                ('text_ru', models.TextField(verbose_name='описание на русском')),
                ('text_en', models.TextField(verbose_name='описание на английском')),
                ('is_reward', models.BooleanField(default=False, verbose_name='показывать надпись: вознаграждение гарантируется')),
                ('show_danger_label', models.BooleanField(default=False, verbose_name='показывать надпись: внимание похищенная вещь')),
                ('media', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, upload_to='media/', verbose_name='медиа-файлы'), size=None)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.category', verbose_name='категория')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_change_users', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_create_users', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.district', verbose_name='район')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.region', verbose_name='область')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ('-date_of_creation',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='активность')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядковый номер')),
                ('title_kk', models.CharField(max_length=300, verbose_name='наименование на казахском')),
                ('title_ru', models.CharField(max_length=300, verbose_name='наименование на русском')),
                ('title_en', models.CharField(verbose_name='наименование на английском')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='json данные')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='test_change_users', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='test_create_users', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор системы'), ('item_edit', 'Оператор корректировки объявлений'), ('info_edit', 'Оператор корректировки новостей'), ('test_edit', 'Оператор корректировки опросов')], max_length=50, verbose_name='роль')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'роль пользователя',
                'verbose_name_plural': 'роли пользователей',
            },
        ),
    ]
