# Generated by Django 5.0.1 on 2024-01-18 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='json данные')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('change_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='test_result_change_users', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='test_result_create_users', to=settings.AUTH_USER_MODEL, verbose_name='кем создан')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.test', verbose_name='тест')),
            ],
            options={
                'verbose_name': 'результат теста',
                'verbose_name_plural': 'результаты теста',
            },
        ),
    ]
