# Generated by Django 5.0.1 on 2024-01-18 05:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_testresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='медиа-файлы'), size=None),
        ),
    ]
