# Generated by Django 4.2.3 on 2024-01-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_item_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='media',
        ),
        migrations.RemoveField(
            model_name='item',
            name='media',
        ),
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/items/', verbose_name='файл')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='main.item', verbose_name='объявление')),
            ],
        ),
        migrations.CreateModel(
            name='InfoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/info/', verbose_name='файл')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='files', to='main.info', verbose_name='объявление')),
            ],
        ),
    ]
