# Generated by Django 5.0.1 on 2024-01-19 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_itemfile_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_change_users', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен'),
        ),
        migrations.AlterField(
            model_name='info',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='info_create_users', to=settings.AUTH_USER_MODEL, verbose_name='кем создан'),
        ),
        migrations.AlterField(
            model_name='infofile',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.info', verbose_name='новость'),
        ),
        migrations.AlterField(
            model_name='item',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_change_users', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен'),
        ),
        migrations.AlterField(
            model_name='item',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_create_users', to=settings.AUTH_USER_MODEL, verbose_name='кем создан'),
        ),
        migrations.AlterField(
            model_name='itemfile',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.item', verbose_name='объявление'),
        ),
        migrations.AlterField(
            model_name='test',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_change_users', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен'),
        ),
        migrations.AlterField(
            model_name='test',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_create_users', to=settings.AUTH_USER_MODEL, verbose_name='кем создан'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='change_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_result_change_users', to=settings.AUTH_USER_MODEL, verbose_name='кем изменен'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='test_result_create_users', to=settings.AUTH_USER_MODEL, verbose_name='кем создан'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.test', verbose_name='тест'),
        ),
    ]
