# Generated by Django 5.0.1 on 2024-01-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_info_change_user_alter_info_create_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание на английском'),
        ),
        migrations.AlterField(
            model_name='info',
            name='text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='описание на казахском'),
        ),
        migrations.AlterField(
            model_name='info',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание на русском'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на английском'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на казахском'),
        ),
        migrations.AlterField(
            model_name='info',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на русском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_of_action',
            field=models.DateField(blank=True, null=True, verbose_name='дата происшествия (утери/похищения)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='punkt_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='населеный пункт на английском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='punkt_kk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='населеный пункт на казахском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='punkt_ru',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='населеный пункт на русском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='описание на английском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='описание на казахском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='описание на русском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='time_of_action',
            field=models.TimeField(blank=True, null=True, verbose_name='время происшествия (утери/похищения)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на английском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на казахском'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на русском'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на английском'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title_kk',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на казахском'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='наименование на русском'),
        ),
    ]
