# Generated by Django 5.0.1 on 2024-01-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_info_text_en_alter_info_text_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.JSONField(blank=True, null=True, verbose_name='детали'),
        ),
    ]
