# Generated by Django 4.2.5 on 2024-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='infofile',
            name='file',
            field=models.FileField(upload_to='info/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='itemfile',
            name='file',
            field=models.FileField(upload_to='items/', verbose_name='файл'),
        ),
    ]
