# Generated by Django 4.2.5 on 2024-01-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comment_text_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='change_user',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='date_of_change',
        ),
    ]
