# Generated by Django 4.2.5 on 2024-01-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='фамилия'),
        ),
    ]
