# Generated by Django 4.2.5 on 2024-01-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_myuser_name_alter_myuser_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='аватар'),
        ),
    ]
